---
name: "ðŸš€ Deploy"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
    paths: ["docs/**", ".github", ".github/workflows/deploy-call.yml"]
  workflow_dispatch:

jobs:
  deploy:
    name: "ðŸš€ Deploy"
    uses: z-shell/.github/.github/workflows/deploy-call.yml@main
    secrets:
      personal_token: ${{ secrets.GH_PAT }}
#     deploy_key: ''
#     external_repository: ''
#     publish_branch: ''
#     publish_dir: ''
#     destination_dir: ''
#     cname: ''
#     keep_files: true
#     allow_empty_commit: true
