---
name: 'ðŸš€ Deploy'
on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  deploy:
    name: 'ðŸš€ Deploy'
    uses: z-shell/.github/.github/workflows/deploy-call.yml@main
#    with:
#      secrets: 
#        personal_token
#        deploy_key: ''
#      external_repository: ''
#      publish_branch: ''
#      publish_dir: ''
#      destination_dir: ''
#      cname: ''
#      keep_files: true
#      allow_empty_commit: true
